name: 'Gitemote'
description: 'Post emote reaction as comments for neew PRs'
author: 'Cristian Richards - rcmtcristian'
branding:
  icon: 'camera'  
  color: 'purple'
inputs:
  github-token:
    description: 'Pass in secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
